-- local exampleGunsParams = {

--     ["Base.example1"] = {                         ------ the item script name "base.AssaultRifle" Base.Shotgun, this is how we find the weapon in our hands
--         casing         = "Base.Bullets44_Casing", ------ the casing item that will be ejected, call the item script
--         ammo           = "Base.Bullets44",        ------ same as for the ammo of the gun, needed for when we do racking
--         forwardOffset  = 0.50,                    ------ how forward the inital spawn is in relation to where the player is looking
--         sideOffset     = 0.0,                     ------ same as above but sideways
--         heightOffset   = 0.45,                    ------ how hight will be the inital spawn
--         shellForce     = 0.85,                    ------ how strong the bullet flies away from the character
--         manualEjection = false,                   ------ is racking is required to eject the spent casing
--         sideSpread     = 55,                      ------ deviation horizontally of casins spread from each other
--         heightSpread   = 55,                      ------ deviation in in regards of how high they fly in flytime, can take {x, x} double values to ensure a casing always achieve a range of min and max
--         ejectAngle     = 0,                       ------ based on degrees 0 is the direction of the player facing, rotates clockwise, 90 will be to the right, 180 behind, etc
--         verticalForce  = -0.5                     ------ This is a multiplayer, is best only used if you want to eject a casing towards the floor, small numbers will do the trick. if you want to achieve higher fly times use the heightSpread.
--     },

--     ["Base.example2"] = {
--         casing         = "Base.Bullets44_Casing",
--         ammo           = "Base.Bullets44",
--         forwardOffset  = 0.50,
--         sideOffset     = 0.0,
--         heightOffset   = 0.45,
--         shellForce     = 0.85,
--         manualEjection = false,
--         sideSpread     = 55,
--         heightSpread   = 55
--     },

--     ["Base.example3"] = {
--         casing         = "Base.Bullets44_Casing",
--         ammo           = "Base.Bullets44",
--         forwardOffset  = 0.50,
--         sideOffset     = 0.0,
--         heightOffset   = 0.45,
--         shellForce     = 0.85,
--         manualEjection = false,
--         sideSpread     = 55,
--         heightSpread   = 55
--     },
-- }

-- for weapon, data in pairs(exampleGunsParams) do
--     SpentCasingPhysics.registerWeapon(
--         weapon,
--         data.casing,
--         data.ammo,
--         data.forwardOffset,
--         data.sideOffset,
--         data.heightOffset,
--         data.shellForce,
--         data.manualEjection,
--         data.sideSpread,
--         data.heightSpread,
--         data.ejectAngle,
--         data.verticalForce
--     )
-- end
