require 'Items/SuburbsDistributions'
require 'Items/ProceduralDistributions'
require "Items/ItemPicker"

-- bedroom
table.insert(ProceduralDistributions["list"]["BedroomSidetable"].items, "PawLowRelooted.smallback")
table.insert(ProceduralDistributions["list"]["BedroomSidetable"].items, 0.8)
table.insert(ProceduralDistributions["list"]["BedroomSidetable"].items, "PawLowRelooted.medbag")
table.insert(ProceduralDistributions["list"]["BedroomSidetable"].items, 0.5)
table.insert(ProceduralDistributions["list"]["BedroomSidetable"].items, "Leggings_Bottoms")
table.insert(ProceduralDistributions["list"]["BedroomSidetable"].items, 1.5)

-- optometrist
table.insert(ProceduralDistributions["list"]["OptometristDesk"].items, "PawLowRelooted.GlassesPLL")
table.insert(ProceduralDistributions["list"]["OptometristDesk"].items, 3)
table.insert(ProceduralDistributions["list"]["OptometristDesk"].items, "PawLowRelooted.GlassesPLLR")
table.insert(ProceduralDistributions["list"]["OptometristDesk"].items, 3)

-- aesthetic
-- table.insert(distributionTable.aesthetic.counter.items, "PawLowRelooted.Hat_HairP")
-- table.insert(distributionTable.aesthetic.counter.items, 2)
-- table.insert(distributionTable.aesthetic.counter.items, "PawLowRelooted.Hat_HairPiggy")
-- table.insert(distributionTable.aesthetic.counter.items, 2)
-- table.insert(distributionTable.aesthetic.counter.items, "PawLowRelooted.Hat_HairModern")
-- table.insert(distributionTable.aesthetic.counter.items, 2)
-- table.insert(distributionTable.aesthetic.counter.items, "PawLowRelooted.Hat_HairWide")
-- table.insert(distributionTable.aesthetic.counter.items, 2)
-- table.insert(distributionTable.aesthetic.counter.items, "PawLowRelooted.Hat_HairWendy")
-- table.insert(distributionTable.aesthetic.counter.items, 2)
-- table.insert(distributionTable.aesthetic.counter.items, "PawLowRelooted.Hat_HairBun2")
-- table.insert(distributionTable.aesthetic.counter.items, 2)
-- table.insert(distributionTable.aesthetic.counter.items, "PawLowRelooted.Hat_HairCroft")
-- table.insert(distributionTable.aesthetic.counter.items, 2)
-- table.insert(distributionTable.aesthetic.counter.items, "PawLowRelooted.Hat_HairFio")
-- table.insert(distributionTable.aesthetic.counter.items, 2)
-- table.insert(distributionTable.aesthetic.counter.items, "PawLowRelooted.Hat_HairMarcel")
-- table.insert(distributionTable.aesthetic.counter.items, 2)
-- table.insert(distributionTable.aesthetic.counter.items, "PawLowRelooted.Animask1")
-- table.insert(distributionTable.aesthetic.counter.items, 1)
-- table.insert(distributionTable.aesthetic.counter.items, "PawLowRelooted.Animask2")
-- table.insert(distributionTable.aesthetic.counter.items, 0.5)
-- table.insert(distributionTable.aesthetic.counter.items, "PawLowRelooted.Animask12")
-- table.insert(distributionTable.aesthetic.counter.items, 1)
-- table.insert(distributionTable.aesthetic.counter.items, "PawLowRelooted.Animask22")
-- table.insert(distributionTable.aesthetic.counter.items, 0.5)

-- clothesstore
table.insert(ProceduralDistributions["list"]["CampingStoreClothes"].items, "PawLowRelooted.medbag2")
table.insert(ProceduralDistributions["list"]["CampingStoreClothes"].items, 0.5)
table.insert(ProceduralDistributions["list"]["CampingStoreClothes"].items, "PawLowRelooted.strapchest")
table.insert(ProceduralDistributions["list"]["CampingStoreClothes"].items, 0.5)
table.insert(ProceduralDistributions["list"]["CampingStoreClothes"].items, "PawLowRelooted.BeltRig")
table.insert(ProceduralDistributions["list"]["CampingStoreClothes"].items, 0.7)
table.insert(ProceduralDistributions["list"]["CampingStoreClothes"].items, "PawLowRelooted.ElbowbandL")
table.insert(ProceduralDistributions["list"]["CampingStoreClothes"].items, 1)
table.insert(ProceduralDistributions["list"]["CampingStoreClothes"].items, "PawLowRelooted.ElbowbandR")
table.insert(ProceduralDistributions["list"]["CampingStoreClothes"].items, 1)
table.insert(ProceduralDistributions["list"]["CampingStoreClothes"].items, "PawLowRelooted.Leggings_Bottoms")
table.insert(ProceduralDistributions["list"]["CampingStoreClothes"].items, 1.5)
table.insert(ProceduralDistributions["list"]["CampingStoreClothes"].items, "PawLowRelooted.Shoes_CanvasshoesLong")
table.insert(ProceduralDistributions["list"]["CampingStoreClothes"].items, 2)
table.insert(ProceduralDistributions["list"]["CampingStoreClothes"].items, "PawLowRelooted.Shoes_Canvasshoes")
table.insert(ProceduralDistributions["list"]["CampingStoreClothes"].items, 3)

-- gunstore
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, "PawLowRelooted.Vest_WitchyCarrier")
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, 0.5)
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, "PawLowRelooted.RogueMask")
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, 0.5)
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, "PawLowRelooted.RogueWaistBag")
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, 0.5)
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, "PawLowRelooted.strapchest")
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, 0.5)
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, "PawLowRelooted.MVest")
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, 0.3)

-- gunstorestorage
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, "PawLowRelooted.Vest_WitchyCarrier")
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, 0.6)
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, "PawLowRelooted.Shoes_Rogue")
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, 0.2)
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, "PawLowRelooted.Gloves_Rogue")
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, 0.3)
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, "PawLowRelooted.medbag2")
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, 0.2)
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, "PawLowRelooted.RogueMask")
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, 0.5)

-- armysurplus
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.ClericPants")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.HATELA")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.3)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.ClericNeck")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.WetSuit")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.Vest_WitchyCarrier")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.6)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.RogueGreaves")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.RogueArms")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.Shoes_Rogue")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.Gloves_Rogue")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.RogueWaist")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.Vest_RogueVest")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.RogueHoodie")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.RogueMask")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.strapchest")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.MVest")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.TacticalWaistBagBack")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.4)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.TacticalWaistBagBackMed")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.4)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.HolsterPLL2M")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 2)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.medbag")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.6)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.medbag2")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.6)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.FlatCap")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 1.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.smallback")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.8)
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "PawLowRelooted.ClericPants")
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "PawLowRelooted.HATELA")
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 0.3)
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "PawLowRelooted.ClericNeck")
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "PawLowRelooted.Hat_Altyn")
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 0.6)
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "PawLowRelooted.WetSuit")
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "PawLowRelooted.Vest_WitchyCarrier")
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 0.6)
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "PawLowRelooted.RogueGreaves")
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "PawLowRelooted.RogueArms")
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "PawLowRelooted.Shoes_Rogue")
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "PawLowRelooted.Gloves_Rogue")
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "PawLowRelooted.RogueWaist")
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "PawLowRelooted.Vest_RogueVest")
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "PawLowRelooted.RogueHoodie")
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "PawLowRelooted.RogueMask")
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "PawLowRelooted.strapchest")
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "PawLowRelooted.MVest")
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "PawLowRelooted.TacticalWaistBagBack")
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 0.4)
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "PawLowRelooted.TacticalWaistBagBackMed")
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 0.4)
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "PawLowRelooted.HolsterPLL2M")
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 2)
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "PawLowRelooted.medbag")
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 0.6)
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "PawLowRelooted.medbag2")
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 0.6)
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "PawLowRelooted.FlatCap")
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 1.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "PawLowRelooted.smallback")
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 0.8)

-- armysurplus clothingrack
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.WetSuit")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.Vest_WitchyCarrier")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.6)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.RogueWaist")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.Vest_RogueVest")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.RogueHoodie")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.strapchest")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "Base.MVest")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "TacticalWaistBagBack")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.4)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "TacticalWaistBagBackMed")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.4)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.HolsterPLL2M")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 2)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "Base.medbag")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.6)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "Base.medbag2")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.6)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.FlatCap")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 1.5)
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, "PawLowRelooted.smallback")
table.insert(ProceduralDistributions["list"]["ArmySurplusOutfit"].items, 0.8)

-- armyhanger
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, "PawLowRelooted.Hat_Altyn")
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, 0.6)
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, "PawLowRelooted.WetSuit")
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, "PawLowRelooted.RogueGreaves")
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, "PawLowRelooted.RogueArms")
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, "PawLowRelooted.Shoes_Rogue")
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, "PawLowRelooted.Gloves_Rogue")
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, "PawLowRelooted.RogueWaist")
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, "PawLowRelooted.Vest_RogueVest")
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, "PawLowRelooted.RogueHoodie")
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, "PawLowRelooted.RogueMask")
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, "PawLowRelooted.strapchest")
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, "PawLowRelooted.MVest")
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, "PawLowRelooted.TacticalWaistBagBack")
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, 0.4)
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, "PawLowRelooted.TacticalWaistBagBackMed")
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, 0.4)
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, "PawLowRelooted.HolsterPLL2M")
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, 2)
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, "PawLowRelooted.medbag")
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, 0.6)
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, "PawLowRelooted.medbag2")
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, 0.6)
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, "PawLowRelooted.FlatCap")
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, 1.5)
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, "PawLowRelooted.smallback")
table.insert(ProceduralDistributions["list"]["ArmyBunkerStorage"].items, 0.8)

-- sportstore
table.insert(ProceduralDistributions["list"]["SportStoreAccessories"].items, "PawLowRelooted.WetSuit")
table.insert(ProceduralDistributions["list"]["SportStoreAccessories"].items, 0.5)
table.insert(ProceduralDistributions["list"]["SportStoreAccessories"].items, "PawLowRelooted.TacticalWaistBagBackMed")
table.insert(ProceduralDistributions["list"]["SportStoreAccessories"].items, 0.3)
table.insert(ProceduralDistributions["list"]["SportStoreAccessories"].items, "PawLowRelooted.TacticalWaistBagBack")
table.insert(ProceduralDistributions["list"]["SportStoreAccessories"].items, 0.3)
table.insert(ProceduralDistributions["list"]["SportStoreAccessories"].items, "PawLowRelooted.ElbowbandL")
table.insert(ProceduralDistributions["list"]["SportStoreAccessories"].items, 0.5)
table.insert(ProceduralDistributions["list"]["SportStoreAccessories"].items, "PawLowRelooted.ElbowbandR")
table.insert(ProceduralDistributions["list"]["SportStoreAccessories"].items, 0.5)
table.insert(ProceduralDistributions["list"]["SportStoreAccessories"].items, "PawLowRelooted.PFVest")
table.insert(ProceduralDistributions["list"]["SportStoreAccessories"].items, 0.5)
table.insert(ProceduralDistributions["list"]["SportStoreAccessories"].items, "PawLowRelooted.CropTop")
table.insert(ProceduralDistributions["list"]["SportStoreAccessories"].items, 0.5)
table.insert(ProceduralDistributions["list"]["SportStoreAccessories"].items, "PawLowRelooted.PFCropped")
table.insert(ProceduralDistributions["list"]["SportStoreAccessories"].items, 0.5)
table.insert(ProceduralDistributions["list"]["SportStoreAccessories"].items, "PawLowRelooted.PFShorts")
table.insert(ProceduralDistributions["list"]["SportStoreAccessories"].items, 0.5)
table.insert(ProceduralDistributions["list"]["SportStoreAccessories"].items, "PawLowRelooted.PFKnee")
table.insert(ProceduralDistributions["list"]["SportStoreAccessories"].items, 0.5)
table.insert(ProceduralDistributions["list"]["SportStoreAccessories"].items, "PawLowRelooted.PFPants")
table.insert(ProceduralDistributions["list"]["SportStoreAccessories"].items, 0.5)
table.insert(ProceduralDistributions["list"]["SportStoreAccessories"].items, "PawLowRelooted.ShorterDenim")
table.insert(ProceduralDistributions["list"]["SportStoreAccessories"].items, 0.4)
table.insert(ProceduralDistributions["list"]["SportStoreAccessories"].items, "PawLowRelooted.strapchest")
table.insert(ProceduralDistributions["list"]["SportStoreAccessories"].items, 0.4)
table.insert(ProceduralDistributions["list"]["SportStoreAccessories"].items, "PawLowRelooted.Shoes_CanvasshoesLong")
table.insert(ProceduralDistributions["list"]["SportStoreAccessories"].items, 1.5)
table.insert(ProceduralDistributions["list"]["SportStoreAccessories"].items, "PawLowRelooted.Shoes_Canvasshoes")
table.insert(ProceduralDistributions["list"]["SportStoreAccessories"].items, 2)
table.insert(ProceduralDistributions["list"]["SportStoreSneakers"].items, "PawLowRelooted.WetSuit")
table.insert(ProceduralDistributions["list"]["SportStoreSneakers"].items, 0.5)
table.insert(ProceduralDistributions["list"]["SportStoreSneakers"].items, "PawLowRelooted.smallback")
table.insert(ProceduralDistributions["list"]["SportStoreSneakers"].items, 1.5)

-- policestorage
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "PawLowRelooted.Vest_WitchyCarrier")
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 0.8)
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "PawLowRelooted.HolsterPLL2")
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 3)
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "PawLowRelooted.BeltRig")
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 0.5)
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "PawLowRelooted.TacticalWaistBagBack")
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 0.5)
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "PawLowRelooted.ClericPants")
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 0.5)
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "PawLowRelooted.HATELA")
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 0.2)
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "PawLowRelooted.ClericNeck")
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 0.5)
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "PawLowRelooted.medbag2")
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 1)
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "PawLowRelooted.strapchest")
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 0.5)
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "PawLowRelooted.MVest")
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 0.5)
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "PawLowRelooted.FlatCap")
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 1)
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "PawLowRelooted.Vest_WitchyCarrier")
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 0.8)
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "PawLowRelooted.Hat_Altyn")
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 0.6)
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "PawLowRelooted.HolsterPLL2")
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 3)
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "PawLowRelooted.BeltRig")
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 2)
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "PawLowRelooted.TacticalWaistBagBack")
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 0.8)
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "PawLowRelooted.ClericPants")
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 0.5)
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "PawLowRelooted.HATELA")
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 0.2)
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "PawLowRelooted.ClericNeck")
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 0.5)
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "PawLowRelooted.medbag2")
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 0.7)
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "PawLowRelooted.strapchest")
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 0.5)
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "PawLowRelooted.MVest")
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 0.3)
table.insert(ProceduralDistributions["list"]["PoliceDesk"].items, "PawLowRelooted.Vest_WitchyCarrier")
table.insert(ProceduralDistributions["list"]["PoliceDesk"].items, 0.8)
table.insert(ProceduralDistributions["list"]["PoliceDesk"].items, "PawLowRelooted.HolsterPLL2")
table.insert(ProceduralDistributions["list"]["PoliceDesk"].items, 3)
table.insert(ProceduralDistributions["list"]["PoliceDesk"].items, "PawLowRelooted.BeltRig")
table.insert(ProceduralDistributions["list"]["PoliceDesk"].items, 2)
table.insert(ProceduralDistributions["list"]["PoliceDesk"].items, "PawLowRelooted.TacticalWaistBagBack")
table.insert(ProceduralDistributions["list"]["PoliceDesk"].items, 0.8)
table.insert(ProceduralDistributions["list"]["PoliceDesk"].items, "PawLowRelooted.HATELA")
table.insert(ProceduralDistributions["list"]["PoliceDesk"].items, 0.2)
table.insert(ProceduralDistributions["list"]["PoliceDesk"].items, "PawLowRelooted.medbag2")
table.insert(ProceduralDistributions["list"]["PoliceDesk"].items, 0.7)
table.insert(ProceduralDistributions["list"]["PoliceDesk"].items, "PawLowRelooted.strapchest")
table.insert(ProceduralDistributions["list"]["PoliceDesk"].items, 0.5)

-- medclinic
table.insert(ProceduralDistributions["list"]["MedicalOfficeCounter"].items, "PawLowRelooted.medbag")
table.insert(ProceduralDistributions["list"]["MedicalOfficeCounter"].items, 0.4)
table.insert(ProceduralDistributions["list"]["MedicalOfficeCounter"].items, "PawLowRelooted.Bag_ParaMedic")
table.insert(ProceduralDistributions["list"]["MedicalOfficeCounter"].items, 0.5)

-- medicalstorage
table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, "PawLowRelooted.TacticalWaistBagBackMed")
table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, 0.3)
table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, "PawLowRelooted.Bag_ParaMedic")
table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, 0.6)

-- pharmacystorage
table.insert(ProceduralDistributions["list"]["PharmacyCosmetics"].items, "PawLowRelooted.TacticalWaistBagBackMed")
table.insert(ProceduralDistributions["list"]["PharmacyCosmetics"].items, 0.3)
table.insert(ProceduralDistributions["list"]["PharmacyCosmetics"].items, "PawLowRelooted.Bag_ParaMedic")
table.insert(ProceduralDistributions["list"]["PharmacyCosmetics"].items, 0.6)
