VFETags = {}

VFETags.Ammo50 = ItemTag.register("vfe:ammo50")
VFETags.Ammo20 = ItemTag.register("vfe:ammo20")
VFETags.Ammo25 = ItemTag.register("vfe:ammo25")

VFETags.AmmoBox50 = ItemTag.register("vfe:ammobox50")
VFETags.AmmoBox20 = ItemTag.register("vfe:ammobox20")
VFETags.AmmoBox25 = ItemTag.register("vfe:ammobox25")

VFETags.AmmoBox = ItemTag.register("vfe:ammobox")
VFETags.AmmoPack = ItemTag.register("vfe:ammopack")
VFETags.AmmoCase = ItemTag.register("vfe:ammocase")
VFETags.AmmoCrate = ItemTag.register("vfe:ammocrate")
VFETags.AmmoCarton = ItemTag.register("vfe:ammocarton")

VFETags.m60_link = ItemTag.register("vfe:m60_link")
VFETags.jamresistant = ItemTag.register("vfe:jamresistant")
VFETags.blockbayonet = ItemTag.register("vfe:blockbayonet")
VFETags.shellreloadboost = ItemTag.register("vfe:shellreloadboost")
VFETags.bulletreloadboost = ItemTag.register("vfe:bulletreloadboost")
VFETags.catchbrass = ItemTag.register("vfe:catchbrass")

VFETags.RPM1000 = ItemTag.register("rpm:1000")
VFETags.RPM950 = ItemTag.register("rpm:950")
VFETags.RPM900 = ItemTag.register("rpm:900")
VFETags.RPM850 = ItemTag.register("rpm:850")
VFETags.RPM800 = ItemTag.register("rpm:800")
VFETags.RPM750 = ItemTag.register("rpm:750")
VFETags.RPM700 = ItemTag.register("rpm:700")
VFETags.RPM650 = ItemTag.register("rpm:650")
VFETags.RPM600 = ItemTag.register("rpm:600")
VFETags.RPM550 = ItemTag.register("rpm:550")
VFETags.RPM500 = ItemTag.register("rpm:500")
VFETags.RPM450 = ItemTag.register("rpm:450")
VFETags.RPM400 = ItemTag.register("rpm:400")
VFETags.RPM350 = ItemTag.register("rpm:350")
VFETags.RPM300 = ItemTag.register("rpm:300")

AmmoType.register("vfe:bullets_762", "Base.762Bullets")
AmmoType.register("vfe:bullets_22", "Base.22Bullets")
AmmoType.register("vfe:bullets_308_linked", "Base.308BulletsLinked")
