local vfeParams = {

    --- Shotguns

    ["Base.Shotgun"] = {
        casing        = "Base.ShotgunShells_Casing",
        ammo          = "Base.ShotgunShells",
        forwardOffset = 0.27,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.25,
        sideSpread    = 30,
        heightSpread  = 30,
        ejectAngle    = 75,
    },

    ["Base.Shotgun2"] = {
        casing        = "Base.ShotgunShells_Casing",
        ammo          = "Base.ShotgunShells",
        forwardOffset = 0.27,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.25,
        sideSpread    = 30,
        heightSpread  = 30,
        ejectAngle    = 75,
    },

    ["Base.ShotgunSemi"] = {
        casing        = "Base.ShotgunShells_Casing",
        ammo          = "Base.ShotgunShells",
        forwardOffset = 0.27,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.35,
        sideSpread    = 30,
        heightSpread  = 30,
    },

    ["Base.ShotgunSemi2"] = {
        casing        = "Base.ShotgunShells_Casing",
        ammo          = "Base.ShotgunShells",
        forwardOffset = 0.27,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.35,
        sideSpread    = 30,
        heightSpread  = 30,
    },

    ["Base.ShotgunSawnoff"] = {
        casing        = "Base.ShotgunShells_Casing",
        ammo          = "Base.ShotgunShells",
        forwardOffset = 0.27,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.25,
        sideSpread    = 30,
        heightSpread  = 30,
        ejectAngle    = 75,
    },

    ["Base.ShotgunSawnoffNoStock"] = {
        casing        = "Base.ShotgunShells_Casing",
        ammo          = "Base.ShotgunShells",
        forwardOffset = 0.27,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.25,
        sideSpread    = 30,
        heightSpread  = 30,
        ejectAngle    = 75,
    },

    ["Base.DoubleBarrelShotgun"] = {
        casing        = "Base.ShotgunShells_Casing",
        ammo          = "Base.ShotgunShells",
        forwardOffset = 0.27,
        sideOffset    = 0.0,
        heightOffset  = 0.45,
        shellForce    = 0.15,
        sideSpread    = 30,
        heightSpread  = { 80, 100 },
        ejectAngle    = 180,
    },

    ["Base.DoubleBarrelShotgunSawnoff"] = {
        casing        = "Base.ShotgunShells_Casing",
        ammo          = "Base.ShotgunShells",
        forwardOffset = 0.27,
        sideOffset    = 0.0,
        heightOffset  = 0.45,
        shellForce    = 0.15,
        sideSpread    = 30,
        heightSpread  = { 80, 100 },
        ejectAngle    = 180,
    },

    ["Base.DoubleBarrelShotgunSawnoffNoStock"] = {
        casing        = "Base.ShotgunShells_Casing",
        ammo          = "Base.ShotgunShells",
        forwardOffset = 0.27,
        sideOffset    = 0.0,
        heightOffset  = 0.45,
        shellForce    = 0.15,
        sideSpread    = 30,
        heightSpread  = { 80, 100 },
        ejectAngle    = 180,
    },

    ["Base.Spas12"] = {
        casing        = "Base.ShotgunShells_Casing",
        ammo          = "Base.ShotgunShells",
        forwardOffset = 0.27,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.25,
        sideSpread    = 30,
        heightSpread  = 30,
        ejectAngle    = 75,
    },

    ["Base.Spas12Folded"] = {
        casing        = "Base.ShotgunShells_Casing",
        ammo          = "Base.ShotgunShells",
        forwardOffset = 0.27,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.25,
        sideSpread    = 30,
        heightSpread  = 30,
        ejectAngle    = 75,
    },

    ["Base.ShotgunSilent"] = {
        casing        = "Base.ShotgunShells_Casing",
        ammo          = "Base.ShotgunShells",
        forwardOffset = 0.35,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.25,
        sideSpread    = 30,
        heightSpread  = 30,
        ejectAngle    = 75,
    },

    --- Rifles

    ["Base.AK47Unfolded"] = {
        casing        = "Base.762Bullets_Casing",
        ammo          = "Base.762Bullets",
        forwardOffset = 0.35,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.85,
        sideSpread    = 60,
        heightSpread  = 90,
        ejectAngle    = 55,
    },

    ["Base.AK47Folded"] = {
        casing        = "Base.762Bullets_Casing",
        ammo          = "Base.762Bullets",
        forwardOffset = 0.35,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.85,
        sideSpread    = 60,
        heightSpread  = 90,
        ejectAngle    = 55,
    },

    ["Base.AK47"] = {
        casing        = "Base.762Bullets_Casing",
        ammo          = "Base.762Bullets",
        forwardOffset = 0.35,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.85,
        sideSpread    = 60,
        heightSpread  = 90,
        ejectAngle    = 55,
    },

    ["Base.MAK90"] = {
        casing        = "Base.762Bullets_Casing",
        ammo          = "Base.762Bullets",
        forwardOffset = 0.30,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.80,
        sideSpread    = 60,
        heightSpread  = 90,
        ejectAngle    = 55,
    },

    ["Base.SKS"] = {
        casing        = "Base.762Bullets_Casing",
        ammo          = "Base.762Bullets",
        forwardOffset = 0.35,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.40,
        sideSpread    = 30,
        heightSpread  = { 70, 90 },
        ejectAngle    = 25,
    },

    ["Base.SKSSpiker"] = {
        casing        = "Base.762Bullets_Casing",
        ammo          = "Base.762Bullets",
        forwardOffset = 0.35,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.40,
        sideSpread    = 30,
        heightSpread  = { 70, 90 },
        ejectAngle    = 25,
    },

    ["Base.1022"] = {
        casing        = "Base.22Bullets_Casing",
        ammo          = "Base.22Bullets",
        forwardOffset = 0.30,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.55,
        sideSpread    = 60,
        heightSpread  = 30,
    },

    ["Base.Mini14Unfolded"] = {
        casing        = "Base.223Bullets_Casing",
        ammo          = "Base.223Bullets",
        forwardOffset = 0.35,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.50,
        sideSpread    = 90,
        heightSpread  = { 80, 90 },
        ejectAngle    = 25,
    },

    ["Base.Mini14Folded"] = {
        casing        = "Base.223Bullets_Casing",
        ammo          = "Base.223Bullets",
        forwardOffset = 0.35,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.50,
        sideSpread    = 90,
        heightSpread  = { 80, 90 },
        ejectAngle    = 25,
    },

    ["Base.Mini14"] = {
        casing        = "Base.223Bullets_Casing",
        ammo          = "Base.223Bullets",
        forwardOffset = 0.35,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.50,
        sideSpread    = 90,
        heightSpread  = { 80, 90 },
        ejectAngle    = 25,
    },

    ["Base.FAL"] = {
        casing        = "Base.308Bullets_Casing",
        ammo          = "Base.308Bullets",
        forwardOffset = 0.40,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.85,
        sideSpread    = 60,
        heightSpread  = 90,
        ejectAngle    = 80,
    },

    ["Base.FALClassic"] = {
        casing        = "Base.308Bullets_Casing",
        ammo          = "Base.308Bullets",
        forwardOffset = 0.40,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.85,
        sideSpread    = 60,
        heightSpread  = 90,
        ejectAngle    = 80,
    },

    ["Base.CAR15"] = {
        casing        = "Base.556Bullets_Casing",
        ammo          = "Base.556Bullets",
        forwardOffset = 0.30,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.85,
        sideSpread    = 60,
        heightSpread  = 30,
        ejectAngle    = 75,
    },

    ["Base.CAR15Folded"] = {
        casing        = "Base.556Bullets_Casing",
        ammo          = "Base.556Bullets",
        forwardOffset = 0.30,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.85,
        sideSpread    = 60,
        heightSpread  = 30,
        ejectAngle    = 75,
    },

    ["Base.CAR15D"] = {
        casing        = "Base.556Bullets_Casing",
        ammo          = "Base.556Bullets",
        forwardOffset = 0.30,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.85,
        sideSpread    = 10,
        heightSpread  = 30,
        ejectAngle    = 65,
    },

    ["Base.CAR15DFolded"] = {
        casing        = "Base.556Bullets_Casing",
        ammo          = "Base.556Bullets",
        forwardOffset = 0.30,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.75,
        sideSpread    = 60,
        heightSpread  = 30,
        ejectAngle    = 75,
    },

    ["Base.AssaultRifle2"] = {
        casing        = "Base.308Bullets_Casing",
        ammo          = "Base.308Bullets",
        forwardOffset = 0.35,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.55,
        sideSpread    = 90,
        heightSpread  = { 80, 90 },
        ejectAngle    = 25,
    },

    ["Base.AssaultRifleM1"] = {
        casing        = "Base.308Bullets_Casing",
        ammo          = "Base.308Bullets",
        forwardOffset = 0.35,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.40,
        sideSpread    = 90,
        heightSpread  = { 80, 90 },
        ejectAngle    = 10,
        verticalForce = 0.1,
    },

    ["Base.AssaultRifle"] = {
        casing        = "Base.556Bullets_Casing",
        ammo          = "Base.556Bullets",
        forwardOffset = 0.30,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.75,
        sideSpread    = 60,
        heightSpread  = 30,
        ejectAngle    = 75,
    },

    ["Base.AssaultRifleMasterkeyShotgun"] = {
        casing        = "Base.ShotgunShells_Casing",
        ammo          = "Base.ShotgunShells",
        forwardOffset = 0.50,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.60,
        sideSpread    = 60,
        heightSpread  = 30,
    },

    ["Base.AssaultRifleMasterkey"] = {
        casing        = "Base.556Bullets_Casing",
        ammo          = "Base.556Bullets",
        forwardOffset = 0.30,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.75,
        sideSpread    = 60,
        heightSpread  = 30,
        ejectAngle    = 75,
    },

    ["Base.M60MMG"] = {
        casing        = "Base.308Bullets_Casing",
        ammo          = "Base.308Bullets",
        forwardOffset = 0.30,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.80,
        sideSpread    = 60,
        heightSpread  = 30,
    },

    ["Base.M60MMG_Bipod"] = {
        casing        = "Base.308Bullets_Casing",
        ammo          = "Base.308Bullets",
        forwardOffset = 0.30,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.80,
        sideSpread    = 60,
        heightSpread  = 30,
    },

    ["Base.HuntingRifle"] = {
        casing        = "Base.308Bullets_Casing",
        ammo          = "Base.308Bullets",
        forwardOffset = 0.30,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.45,
        sideSpread    = 30,
        heightSpread  = 30,
    },

    ["Base.VarmintRifle"] = {
        casing        = "Base.223Bullets_Casing",
        ammo          = "Base.223Bullets",
        forwardOffset = 0.15,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.45,
        sideSpread    = 30,
        heightSpread  = 30,
    },

    ["Base.SniperRifle"] = {
        casing        = "Base.308Bullets_Casing",
        ammo          = "Base.308Bullets",
        forwardOffset = 0.25,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.65,
        sideSpread    = 30,
        ejectAngle    = 45,
        heightSpread  = { 70, 100 },
    },

    ["Base.CampCarbine"] = {
        casing        = "Base.Bullets45_Casing",
        ammo          = "Base.Bullets45",
        forwardOffset = 0.35,
        sideOffset    = 0.0,
        heightOffset  = 0.45,
        shellForce    = 0.60,
        sideSpread    = 45,
        heightSpread  = 60,
    },

    ["Base.LeverRifle"] = {
        casing        = "Base.Bullets38_Casing",
        ammo          = "Base.Bullets38",
        forwardOffset = 0.35,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.25,
        sideSpread    = 30,
        heightSpread  = 30,
    },

    ["Base.LeverRifle2"] = {
        casing        = "Base.Bullets44_Casing",
        ammo          = "Base.Bullets44",
        forwardOffset = 0.30,
        sideOffset    = 0.10,
        heightOffset  = 0.45,
        shellForce    = 0.35,
        sideSpread    = 30,
        heightSpread  = 60,
    },

    --- Smgs

    ["Base.MP5"] = {
        casing        = "Base.Bullets9mm_Casing",
        ammo          = "Base.Bullets9mm",
        forwardOffset = 0.30,
        sideOffset    = 0.0,
        heightOffset  = 0.50,
        shellForce    = 0.60,
        sideSpread    = 60,
        heightSpread  = 60,
    },

    ["Base.MP5SD"] = {
        casing        = "Base.Bullets9mm_Casing",
        ammo          = "Base.Bullets9mm",
        forwardOffset = 0.30,
        sideOffset    = 0.0,
        heightOffset  = 0.50,
        shellForce    = 0.60,
        sideSpread    = 60,
        heightSpread  = 60,
    },

    ["Base.MP5Unfolded"] = {
        casing        = "Base.Bullets9mm_Casing",
        ammo          = "Base.Bullets9mm",
        forwardOffset = 0.30,
        sideOffset    = 0.0,
        heightOffset  = 0.50,
        shellForce    = 0.60,
        sideSpread    = 60,
        heightSpread  = 60,
    },

    ["Base.MP5Folded"] = {
        casing        = "Base.Bullets9mm_Casing",
        ammo          = "Base.Bullets9mm",
        forwardOffset = 0.30,
        sideOffset    = 0.0,
        heightOffset  = 0.50,
        shellForce    = 0.60,
        sideSpread    = 60,
        heightSpread  = 60,
    },

    ["Base.MAC10Unfolded"] = {
        casing        = "Base.Bullets45_Casing",
        ammo          = "Base.Bullets45",
        forwardOffset = 0.45,
        sideOffset    = 0.0,
        heightOffset  = 0.50,
        shellForce    = 0.60,
        sideSpread    = 60,
        heightSpread  = 60,
    },

    ["Base.MAC10Folded"] = {
        casing        = "Base.Bullets45_Casing",
        ammo          = "Base.Bullets45",
        forwardOffset = 0.45,
        sideOffset    = 0.0,
        heightOffset  = 0.50,
        shellForce    = 0.60,
        sideSpread    = 30,
        heightSpread  = 60,
    },

    ["Base.UziUnfolded"] = {
        casing        = "Base.Bullets9mm_Casing",
        ammo          = "Base.Bullets9mm",
        forwardOffset = 0.40,
        sideOffset    = 0.0,
        heightOffset  = 0.50,
        shellForce    = 0.60,
        sideSpread    = 30,
        heightSpread  = 60,
    },

    ["Base.UziFolded"] = {
        casing        = "Base.Bullets9mm_Casing",
        ammo          = "Base.Bullets9mm",
        forwardOffset = 0.40,
        sideOffset    = 0.0,
        heightOffset  = 0.50,
        shellForce    = 0.60,
        sideSpread    = 30,
        heightSpread  = 60,
    },

    --- Pistols

    ["Base.Tec9"] = {
        casing        = "Base.Bullets9mm_Casing",
        ammo          = "Base.Bullets9mm",
        forwardOffset = 0.45,
        sideOffset    = 0.0,
        heightOffset  = 0.50,
        shellForce    = 0.60,
        sideSpread    = 45,
        heightSpread  = 60,
    },

    ["Base.Pistol"] = {
        casing        = "Base.Bullets9mm_Casing",
        ammo          = "Base.Bullets9mm",
        forwardOffset = 0.40,
        sideOffset    = 0.0,
        heightOffset  = 0.50,
        shellForce    = 0.60,
        sideSpread    = 45,
        heightSpread  = 60,
    },

    ["Base.Pistol2"] = {
        casing        = "Base.Bullets45_Casing",
        ammo          = "Base.Bullets45",
        forwardOffset = 0.40,
        sideOffset    = 0.0,
        heightOffset  = 0.50,
        shellForce    = 0.60,
        sideSpread    = 45,
        heightSpread  = 90,
    },

    ["Base.Pistol3"] = {
        casing        = "Base.Bullets44_Casing",
        ammo          = "Base.Bullets44",
        forwardOffset = 0.40,
        sideOffset    = 0.0,
        heightOffset  = 0.50,
        shellForce    = 0.30,
        sideSpread    = 30,
        heightSpread  = 60,
    },

    ["Base.MK23SOCOM"] = {
        casing        = "Base.Bullets45_Casing",
        ammo          = "Base.Bullets45",
        forwardOffset = 0.40,
        sideOffset    = 0.0,
        heightOffset  = 0.50,
        shellForce    = 0.60,
        sideSpread    = 50,
        heightSpread  = 45,
    },

    ["Base.Glock"] = {
        casing        = "Base.Bullets9mm_Casing",
        ammo          = "Base.Bullets9mm",
        forwardOffset = 0.40,
        sideOffset    = 0.0,
        heightOffset  = 0.50,
        shellForce    = 0.45,
        sideSpread    = 45,
        heightSpread  = 90,
    },

    ["Base.Glock18"] = {
        casing        = "Base.Bullets9mm_Casing",
        ammo          = "Base.Bullets9mm",
        forwardOffset = 0.40,
        sideOffset    = 0.0,
        heightOffset  = 0.50,
        shellForce    = 0.45,
        sideSpread    = 45,
        heightSpread  = 90,
    },

    ["Base.P229"] = {
        casing        = "Base.Bullets9mm_Casing",
        ammo          = "Base.Bullets9mm",
        forwardOffset = 0.40,
        sideOffset    = 0.0,
        heightOffset  = 0.50,
        shellForce    = 0.60,
        sideSpread    = 45,
        heightSpread  = 90,
    },

    ["Base.CZ75"] = {
        casing        = "Base.Bullets9mm_Casing",
        ammo          = "Base.Bullets9mm",
        forwardOffset = 0.40,
        sideOffset    = 0.0,
        heightOffset  = 0.50,
        shellForce    = 0.79,
        sideSpread    = 30,
        heightSpread  = 90,
    },

    ["Base.MK2"] = {
        casing        = "Base.22Bullets_Casing",
        ammo          = "Base.22Bullets",
        forwardOffset = 0.40,
        sideOffset    = 0.0,
        heightOffset  = 0.50,
        shellForce    = 0.60,
        sideSpread    = 30,
        heightSpread  = 60,
    },

    ["Base.MK2SD"] = {
        casing        = "Base.22Bullets_Casing",
        ammo          = "Base.22Bullets",
        forwardOffset = 0.40,
        sideOffset    = 0.0,
        heightOffset  = 0.50,
        shellForce    = 0.60,
        sideSpread    = 30,
        heightSpread  = 60,
    },

    ["Base.Revolver"] = {
        casing        = "Base.Bullets45_Casing",
        ammo          = "Base.Bullets45",
        forwardOffset = 0.10,
        sideOffset    = 0.0,
        heightOffset  = 0.30,
        shellForce    = 0.10,
        sideSpread    = 30,
        heightSpread  = 30,
    },

    ["Base.Revolver_Short"] = {
        casing        = "Base.Bullets38_Casing",
        ammo          = "Base.Bullets38",
        forwardOffset = 0.10,
        sideOffset    = 0.0,
        heightOffset  = 0.30,
        shellForce    = 0.10,
        sideSpread    = 30,
        heightSpread  = 30,
    },

    ["Base.Revolver_Long"] = {
        casing        = "Base.Bullets44_Casing",
        ammo          = "Base.Bullets44",
        forwardOffset = 0.10,
        sideOffset    = 0.0,
        heightOffset  = 0.30,
        shellForce    = 0.10,
        sideSpread    = 30,
        heightSpread  = 30,
    },

    --- Combination Gun

    ["Base.M2400_Shotgun"] = {
        casing        = "Base.ShotgunShells_Casing",
        ammo          = "Base.ShotgunShells",
        forwardOffset = 0.30,
        sideOffset    = 0.0,
        heightOffset  = 0.40,
        shellForce    = 0.30,
        sideSpread    = 10,
        heightSpread  = { 80, 100 },
        ejectAngle    = 180,
    },

    ["Base.M2400_Rifle"] = {
        casing        = "Base.308Bullets_Casing",
        ammo          = "Base.308Bullets",
        forwardOffset = 0.30,
        sideOffset    = 0.0,
        heightOffset  = 0.40,
        shellForce    = 0.30,
        sideSpread    = 10,
        heightSpread  = { 80, 100 },
        ejectAngle    = 180,
    },
}

if SpentCasingPhysics then
    for weapon, data in pairs(vfeParams) do
        SpentCasingPhysics.registerWeapon(
            weapon,
            data.forwardOffset,
            data.sideOffset,
            data.heightOffset,
            data.shellForce,
            data.sideSpread,
            data.heightSpread,
            data.ejectAngle,
            data.verticalForce
        )
    end
end
